<a href="https://colab.research.google.com/github/bgalerne/IoT_mathematics/blob/master/Lab1_numpy_matrices_tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np
import matplotlib.pyplot as plt

# Numpty tutorial for matrices

NumPy: "The fundamental package for scientific computing with Python"
https://numpy.org/


# Vectors and matrices

## From Python list to numpy array

In [12]:
L = [1, 2, 3, 4]
print(L)
print(type(L))

v = np.array(L)
print(v)
print(type(v))
print(v.dtype)
print(v.shape)

w = np.arange(1,10,2)
print(w)
print(type(w))
print(w.dtype)
print(w.shape)


[1, 2, 3, 4]
<class 'list'>
[1 2 3 4]
<class 'numpy.ndarray'>
int64
(4,)
[1 3 5 7 9]
<class 'numpy.ndarray'>
int64
(5,)
(5,)


## Numpy array and column vectors

In [45]:
v = np.arange(1,10,2)
w = v-3
print([v,w])
print(v*w)

# dot is the dot product, but also the matrix product
print(v.dot(w))
print((v.dot(w)).shape)

print(v.shape)
v.shape = (5,1)
print(v.shape)

# print(v.dot(w)) # error

w.shape = (5,1)
print(v.dot(w.T))
print((v.dot(w.T)).shape)
print(v.T.dot(w))
print((v.T.dot(w)).shape)





[array([1, 3, 5, 7, 9]), array([-2,  0,  2,  4,  6])]
[-2  0 10 28 54]
90
()
(5,)
(5, 1)
[[ -2   0   2   4   6]
 [ -6   0   6  12  18]
 [-10   0  10  20  30]
 [-14   0  14  28  42]
 [-18   0  18  36  54]]
(5, 5)
[[90]]
(1, 1)


## From Python double list to numpy 2D array

Matrices in numpy are 2D arrays. 

In [30]:
L = [[1,2,3],[4,5,6],[7,8,9]]
print(L)
print(type(L))
print(L[0])
print(type(L[0]))
print(L[0][2])
print(type(L[0][2]))

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
<class 'list'>
[1, 2, 3]
<class 'list'>
3
<class 'int'>


In [34]:
M = np.array(L)
print(M)
print(type(M))
print(M.shape)
print(M[0])
print(type(M[0]))
print(M[0][2])
print(type(M[0][2]))
print(M[0,2])
print(type(M[0,2]))


[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>
(3, 3)
[1 2 3]
<class 'numpy.ndarray'>
3
<class 'numpy.int64'>
3
<class 'numpy.int64'>
[1 4 7 2 5 8 3 6 9]


### Flatten a matrix into a 1D array:

np.flatten function: Return a flattened copy of the matrix.

np.ravel: Same but does not make a copy.

In [38]:
# ‘C’ means to flatten in row-major (C-style) order (Numpy default). 
# ‘F’ means to flatten in column-major (Fortran-style) order. 
print(M.flatten('C')) 
print((M.flatten('C')).shape)   
print(M.flatten('F'))
print((M.flatten('F')).shape)



[1 2 3 4 5 6 7 8 9]
(9,)
[1 4 7 2 5 8 3 6 9]
(9,)


### From 1D array to 2D array

In [46]:
a = np.arange(1,24,2)
print(a)
print(a.shape)

[ 1  3  5  7  9 11 13 15 17 19 21 23]
(12,)


In [49]:
b = a.copy()
b.shape=(3,4)
print(b)

[[ 1  3  5  7]
 [ 9 11 13 15]
 [17 19 21 23]]


In [58]:
c = a.copy()
c = np.reshape(c, (3,4),'F')
print(c)

[[ 1  7 13 19]
 [ 3  9 15 21]
 [ 5 11 17 23]]


**Exercice 1:** Construct the matrix c without the reshape function.

**Exercice 2:** Extract the 5th, 7th, and 8th (starting 0) coefficient of c in the column-major order using the np.unravel_index function.

[Doc for unravel_index: https://numpy.org/doc/stable/reference/generated/numpy.unravel_index.html?#numpy.unravel_index](https://numpy.org/doc/stable/reference/generated/numpy.unravel_index.html?#numpy.unravel_index)

## Indexing and slicing