<a href="https://colab.research.google.com/github/bgalerne/IoT_mathematics/blob/master/Lab1_numpy_matrices_tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np
import matplotlib.pyplot as plt

# Numpty tutorial for matrices

NumPy: "The fundamental package for scientific computing with Python"
https://numpy.org/


# Vectors and matrices

## From Python list to numpy array

In [12]:
L = [1, 2, 3, 4]
print(L)
print(type(L))

v = np.array(L)
print(v)
print(type(v))
print(v.dtype)
print(v.shape)

w = np.arange(1,10,2)
print(w)
print(type(w))
print(w.dtype)
print(w.shape)


[1, 2, 3, 4]
<class 'list'>
[1 2 3 4]
<class 'numpy.ndarray'>
int64
(4,)
[1 3 5 7 9]
<class 'numpy.ndarray'>
int64
(5,)
(5,)


## Numpy array and column vectors

In [27]:
v = np.arange(1,10,2)
w = v-3
print([v,w])
print(v*w)

# dot is the dot product, but also the matrix product
print(v.dot(w))
print((v.dot(w)).shape)

print(v.shape)
v.shape = (5,1)
print(v.shape)

# print(v.dot(w)) # error

w.shape = (5,1)
print(v.dot(w.T))
print((v.dot(w.T)).shape)
print(v.T.dot(w))
print((v.T.dot(w)).shape)





[array([1, 3, 5, 7, 9]), array([-2,  0,  2,  4,  6])]
[-2  0 10 28 54]
90
()
(5,)
(5, 1)
[[ -2   0   2   4   6]
 [ -6   0   6  12  18]
 [-10   0  10  20  30]
 [-14   0  14  28  42]
 [-18   0  18  36  54]]
(5, 5)
[[90]]
(1, 1)
