<a href="https://colab.research.google.com/github/bgalerne/IoT_mathematics/blob/master/Lab1_numpy_matrices_tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

# Numpty tutorial for matrices

NumPy: "The fundamental package for scientific computing with Python"
https://numpy.org/


# 1. Vectors and matrices

## From Python list to numpy array

In [ ]:
L = [1, 2, 3, 4]
print(L)
print(type(L))

v = np.array(L)
print(v)
print(type(v))
print(v.dtype)
print(v.shape)

w = np.arange(1,10,2)
print(w)
print(type(w))
print(w.dtype)
print(w.shape)


[1, 2, 3, 4]
<class 'list'>
[1 2 3 4]
<class 'numpy.ndarray'>
int64
(4,)
[1 3 5 7 9]
<class 'numpy.ndarray'>
int64
(5,)
(5,)


## Numpy array and column vectors

In [34]:
v = np.arange(1,10,2)
w = v-3
print([v,w])
print(v*w)

# dot is the dot product, but also the matrix product
print(v.dot(w))
print((v.dot(w)).shape)

print(v.shape)
v.shape = (5,1) # or: v = np.reshape(v,(5,1))
print(v.shape)

# print(v.dot(w)) # error

w.shape = (5,1)
print(v.dot(w.T)) # .T is for transpose
print((v.dot(w.T)).shape)
print(v.T.dot(w))
print((v.T.dot(w)).shape)





[array([1, 3, 5, 7, 9]), array([-2,  0,  2,  4,  6])]
[-2  0 10 28 54]
90
()
(5,)
(5, 1)
[[ -2   0   2   4   6]
 [ -6   0   6  12  18]
 [-10   0  10  20  30]
 [-14   0  14  28  42]
 [-18   0  18  36  54]]
(5, 5)
[[90]]
(1, 1)


## From Python double list to numpy 2D array

Matrices in numpy are 2D arrays. 

In [ ]:
L = [[1,2,3],[4,5,6],[7,8,9]]
print(L)
print(type(L))
print(L[0])
print(type(L[0]))
print(L[0][2])
print(type(L[0][2]))

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
<class 'list'>
[1, 2, 3]
<class 'list'>
3
<class 'int'>


In [ ]:
M = np.array(L)
print(M)
print(type(M))
print(M.shape)
print(M[0])
print(type(M[0]))
print(M[0][2])
print(type(M[0][2]))
print(M[0,2])
print(type(M[0,2]))


[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>
(3, 3)
[1 2 3]
<class 'numpy.ndarray'>
3
<class 'numpy.int64'>
3
<class 'numpy.int64'>
[1 4 7 2 5 8 3 6 9]


### Flatten a matrix into a 1D array

np.flatten function: Return a flattened copy of the matrix.

np.ravel: Same but does not make a copy.

In [ ]:
# ‘C’ means to flatten in row-major (C-style) order (Numpy default). 
# ‘F’ means to flatten in column-major (Fortran-style) order. 
print(M.flatten('C')) 
print((M.flatten('C')).shape)   
print(M.flatten('F'))
print((M.flatten('F')).shape)



[1 2 3 4 5 6 7 8 9]
(9,)
[1 4 7 2 5 8 3 6 9]
(9,)


### From 1D array to 2D array

In [ ]:
a = np.arange(1,24,2)
print(a)
print(a.shape)

[ 1  3  5  7  9 11 13 15 17 19 21 23]
(12,)


In [ ]:
b = a.copy()
b.shape=(3,4)
print(b)

[[ 1  3  5  7]
 [ 9 11 13 15]
 [17 19 21 23]]


In [ ]:
c = a.copy()
c = np.reshape(c, (3,4),'F')
print(c)

[[ 1  7 13 19]
 [ 3  9 15 21]
 [ 5 11 17 23]]


**Exercice 1:** Construct the matrix c without the reshape function.



## Indexing and slicing

In [ ]:
a = np.arange(20)
M = np.reshape(a, (4,5))
print(M)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


### Access to a single coefficient:

In [ ]:
# access to one coefficient:
print(M[2,3])


### Acess to a full row or column:

In [ ]:
print(M[1,:])
print(M[:,3])

### Acess to a submatrix using start:stop:step

In [ ]:
print(M[0:2,1:5])
print(M[0::2,1:5])
print(M[0::2,1:5:3])

[[1 2 3 4]
 [6 7 8 9]]
[[ 1  2  3  4]
 [11 12 13 14]]
[[ 1  4]
 [11 14]]


### Boundary: Periodic indexing

In [ ]:
print(M[[-1, 1],:])

[[15 16 17 18 19]
 [ 5  6  7  8  9]]


In [ ]:
print(M[-2:2,1])
print(M[np.arange(-2,3),1])

[]
[11 16  1  6 11]


### Linear indexing:
It is sometimes necessary to use linear indexing for matrices.



**Exercice 2:** 
Consider the matrix `c` of **Exercice 1**.
Extract the 5th, 7th, and 8th (starting 0) coefficient of `c`  in the column-major order using the `np.unravel_index` function.

[Doc for unravel_index: https://numpy.org/doc/stable/reference/generated/numpy.unravel_index.html?#numpy.unravel_index](https://numpy.org/doc/stable/reference/generated/numpy.unravel_index.html?#numpy.unravel_index)

# 2. Operations on matrices
## Element-wise operations:

In [42]:
v = np.arange(0,20,3)
print(v)
print(v.shape)
r = np.random.rand(v.shape[0])
print(r)
print(v+r)
print(v*r)
print(v/r)
print(r/v)


[ 0  3  6  9 12 15 18]
(7,)
[0.53404336 0.95741514 0.72562111 0.79007865 0.84193251 0.82749908
 0.23316256]
[ 0.53404336  3.95741514  6.72562111  9.79007865 12.84193251 15.82749908
 18.23316256]
[ 0.          2.87224542  4.35372668  7.11070785 10.10319009 12.41248626
  4.19692601]
[ 0.          3.13343698  8.26877815 11.39127098 14.25292395 18.12690828
 77.19935952]
[       inf 0.31913838 0.12093685 0.08778652 0.07016104 0.05516661
 0.01295348]


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:9: RuntimeWarning: divide by zero encountered in true_divide
  if __name__ == '__main__':


## Matrix operations:

In [49]:
a = np.random.rand(4,5)
print(a)
b = np.random.rand(4,5)
print(b)
v = np.random.rand(5,1)
print(v)
print(a+b)
print(a*b)
print(np.dot(a,b.T))
print(a.dot(b.T))

print(a.dot(v))

print(a.dot(b)) # error



[[0.8043879  0.28455851 0.69305737 0.17884143 0.20456732]
 [0.03328463 0.99924799 0.26009357 0.83849798 0.18779583]
 [0.81491306 0.98630676 0.65463665 0.96039573 0.71379741]
 [0.05305245 0.78220252 0.76418861 0.75546859 0.14623255]]
[[0.83474235 0.27859899 0.99086769 0.01124827 0.9333488 ]
 [0.86422552 0.36696514 0.48006524 0.90125565 0.75124892]
 [0.52241042 0.82089051 0.06114042 0.23690346 0.05672166]
 [0.4940761  0.87095418 0.42958632 0.78459355 0.82283454]]
[[0.98088581]
 [0.00581915]
 [0.61792156]
 [0.02252649]
 [0.44443085]]
[[1.63913024 0.56315751 1.68392506 0.1900897  1.13791612]
 [0.89751015 1.36621313 0.74015881 1.73975363 0.93904475]
 [1.33732348 1.80719727 0.71577707 1.19729919 0.77051907]
 [0.54712855 1.65315671 1.19377493 1.54006214 0.96906709]]
[[0.67145664 0.07927772 0.68672815 0.00201166 0.19093266]
 [0.02876543 0.36668918 0.12486188 0.75570104 0.14108141]
 [0.42571907 0.80964986 0.04002476 0.22752107 0.04048777]
 [0.02621195 0.68126256 0.32828497 0.59273578 0.12032519

ValueError: ignored

# 3. Exercice: Patch processing

Consider a signal $a\in\mathbb{R}^n$ with $n$ coefficients.
Given an half-size $s\in\mathbb{N}^*$ we define the patch of $a$ at index $i$ as the vector
$$
(a_{i-s}, a_{i-s+1},\dots, a_{i}, a_{i+1}, \dots, a_{i+s})^T \in \mathbb{R}^{2s+1},
$$
that is the vector obtained in taking the neighborhood of $a_i$ with radius $s$ (with periodic boundary condition).

1. Write a function `array_to_patches_with_loop(a,s)` that constructs a matrix $M$ of size $2s+1\times d$ such that the $i$-th column of $M$ is the patch of $a$ at index $i$ using a for loop.

2. Write a function `array_to_patches_wo_loop(a,s)` that constructs the same matrix without any for loop.

3. Compare the time performance of the two functions as the size of $d$ grows using random signals. Report the result with a graph.

4. Create a signal with
```
n = 256
a = np.linspace(0,10,n) + np.random.randn(n)
```
Extract all the patches with half-size $s=7$ of $a$ and compute the mean of each patches to get a new signal $b\in\mathbb{R}^n$. Plot $a$ and $b$. Comment the result.
