<a href="https://colab.research.google.com/github/bgalerne/IoT_mathematics/blob/master/Lab1_numpy_matrices_tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import matplotlib.pyplot as plt
import time

# Numpty tutorial for matrices

NumPy: "The fundamental package for scientific computing with Python"
https://numpy.org/


# 1. Vectors and matrices

## From Python list to numpy array

In [3]:
L = [1, 2, 3, 4]
print(L)
print(type(L))

v = np.array(L)
print(v)
print(type(v))
print(v.dtype)
print(v.shape)

w = np.arange(1,10,2)
print(w)
print(type(w))
print(w.dtype)
print(w.shape)


[1, 2, 3, 4]
<class 'list'>
[1 2 3 4]
<class 'numpy.ndarray'>
int64
(4,)
[1 3 5 7 9]
<class 'numpy.ndarray'>
int64
(5,)


## Numpy array and column vectors

In [6]:
v = np.arange(1,10,2)
w = v-3
print([v,w])
print(v*w)

# dot is the dot product, but also the matrix product
print(v.dot(w))
print((v.dot(w)).shape)

print(v.shape)
v = np.reshape(v,(5,1)) # or: v.shape = (5,1)
print(v.shape)

# print(v.dot(w)) # error

w.shape = (5,1)
print(v.dot(w.T)) # .T is for transpose
print((v.dot(w.T)).shape)
print(v.T.dot(w))
print((v.T.dot(w)).shape)

print(v.T @ w) # matrix product




[array([1, 3, 5, 7, 9]), array([-2,  0,  2,  4,  6])]
[-2  0 10 28 54]
v.dot(w) 90
()
(5,)
(5, 1)
[[ -2   0   2   4   6]
 [ -6   0   6  12  18]
 [-10   0  10  20  30]
 [-14   0  14  28  42]
 [-18   0  18  36  54]]
(5, 5)
[[90]]
(1, 1)
[[90]]


## From Python double list to numpy 2D array

Matrices in numpy are 2D arrays. 

In [ ]:
L = [[1,2,3],[4,5,6],[7,8,9]]
print(L)
print(type(L))
print(L[0])
print(type(L[0]))
print(L[0][2])
print(type(L[0][2]))

In [ ]:
M = np.array(L)
print(M)
print(type(M))
print(M.shape)
print(M[0])
print(type(M[0]))
print(M[0][2])
print(type(M[0][2]))
print(M[0,2])
print(type(M[0,2]))


### Flatten a matrix into a 1D array

np.flatten function: Return a flattened copy of the matrix.

np.ravel: Same but does not make a copy.

In [ ]:
# ‘C’ means to flatten in row-major (C-style) order (Numpy default). 
# ‘F’ means to flatten in column-major (Fortran-style) order. 
L = [[1,2,3],[4,5,6],[7,8,9]]
M = np.array(L)
print(M)
print(M.flatten('C')) 
print((M.flatten('C')).shape)   
print(M.flatten('F'))
print((M.flatten('F')).shape)
print(M.flatten()) 
print((M.flatten()).shape)   



[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3 4 5 6 7 8 9]
(9,)
[1 4 7 2 5 8 3 6 9]
(9,)
[1 2 3 4 5 6 7 8 9]
(9,)


### From 1D array to 2D array

In [ ]:
a = np.arange(1,24,2)
print(a)
print(a.shape)

[ 1  3  5  7  9 11 13 15 17 19 21 23]
(12,)


In [ ]:
b = a.copy()
b.shape=(3,4)
print(b)

[[ 1  3  5  7]
 [ 9 11 13 15]
 [17 19 21 23]]


In [ ]:
c = a.copy()
c = np.reshape(c, (3,4),'F')
print(c)
#equivalently without the 'F' option: Use matrix transpose.
d = np.reshape(a.copy(),(4,3)).T
print(d)

[[ 1  7 13 19]
 [ 3  9 15 21]
 [ 5 11 17 23]]
[[ 1  7 13 19]
 [ 3  9 15 21]
 [ 5 11 17 23]]


## Indexing and slicing

In [ ]:
a = np.arange(20)
M = np.reshape(a, (4,5))
print(M)

### Access to a single coefficient:

In [ ]:
# access to one coefficient:
print(M[2,3])


### Acess to a full row or column:

In [ ]:
print(M[1,:])
print(M[:,3])

### Acess to a submatrix using start:stop:step

In [ ]:
print(M[0:2,1:5])
print(M[0::2,1:5])
print(M[0::2,1:5:3])

### Boundary: Periodic indexing

In [ ]:
print(M[[-1, 1],:])

In [ ]:
print(M[-2:2,1])
print(M[np.arange(-2,3),1])

### Linear indexing:
It is sometimes necessary to use linear indexing for matrices.



**Exercice 1:** 
Consider the matrix `c` 
```
c = np.reshape(np.arange(1,24,2), (3,4),'F')
```
Extract the 5th, 7th, and 8th (starting 0) coefficient of `c`  in the column-major order using the `np.unravel_index` function.

[Doc for unravel_index: https://numpy.org/doc/stable/reference/generated/numpy.unravel_index.html?#numpy.unravel_index](https://numpy.org/doc/stable/reference/generated/numpy.unravel_index.html?#numpy.unravel_index)

# 2. Operations on matrices
## Element-wise operations:

In [ ]:
v = np.arange(0,20,3)
print(v)
print(v.shape)
r = np.random.rand(v.shape[0])
print(r)
print(v+r)
print(v*r)
print(v/r)
print(r/v)


## Matrix operations:

In [ ]:
a = np.random.rand(4,5)
print(a)
b = np.random.rand(4,5)
print(b)
v = np.random.rand(5,1)
print(v)
print(a+b)
print(a*b)
print(np.dot(a,b.T))
print(a.dot(b.T))

print(a.dot(v))

#print(a.dot(b)) # error

print(a.dot(b.T)) # matrix product

print(a @ b.T) # matrix product


[[0.44534364 0.6387988  0.50528281 0.2127218  0.45194223]
 [0.35786726 0.22739571 0.56142777 0.85490248 0.67105051]
 [0.09310442 0.63971638 0.74696784 0.56470115 0.2238483 ]
 [0.60529147 0.08100329 0.03939178 0.80886176 0.35194499]]
[[0.36593475 0.25538206 0.08311717 0.17015859 0.91407151]
 [0.43534608 0.9138127  0.43711369 0.27656529 0.53751027]
 [0.65410212 0.8132633  0.48292267 0.17985051 0.6819042 ]
 [0.87136395 0.21868282 0.22928638 0.57849376 0.29655473]]
[[0.07473099]
 [0.93067778]
 [0.24620692]
 [0.8970654 ]
 [0.66612243]]
[[0.81127839 0.89418086 0.58839998 0.38288039 1.36601374]
 [0.79321334 1.14120841 0.99854145 1.13146777 1.20856078]
 [0.74720654 1.45297968 1.22989051 0.74455166 0.9057525 ]
 [1.47665542 0.29968611 0.26867815 1.38735552 0.64849973]]
[[0.16296671 0.16313775 0.04199768 0.03619644 0.41310752]
 [0.15579611 0.20779709 0.24540776 0.23643635 0.36069654]
 [0.0608998  0.52025785 0.3607277  0.10156179 0.15264309]
 [0.52742917 0.01771403 0.009032   0.46792148 0.10437095

## Broadcasting:
"The term broadcasting describes how numpy treats arrays with different shapes during arithmetic operations."
This allows e.g. to add an array to all the columns or line of a matrix without duplicating the array.

Please read the numpy manual section on the topics:
https://numpy.org/doc/stable/user/basics.broadcasting.html

**Exercise 2:**
Given a $4\times 4$ matrix $A$ and two arrays $b$ and $c$ of length $4$, construct the following 3 matrices
using only broadcasting and ```np.reshape()``` :


  1. 
  
  $$
M_1 = (a_{i,j}+b_j)_{\substack{1\leq i\leq 4 \\ 1\leq j\leq 4}}
$$

  2.

  $$
M_2 = \left(\frac{a_{i,j}}{b_i}\right)_{\substack{1\leq i\leq 4 \\ 1\leq j\leq 4}} \quad \text{assuming all $b_i\neq 0$}
$$  
  3.

  $$
M_3 = (a_{i,j}b_i c_j)_{\substack{1\leq i\leq 4 \\ 1\leq j\leq 4}} 
$$


# 3. Exercice 3: Patch processing

Consider a signal $a\in\mathbb{R}^n$ with $n$ coefficients.
Given an half-size $s\in\mathbb{N}^*$ we define the patch of $a$ at index $i$ as the vector
$$
(a_{i-s}, a_{i-s+1},\dots, a_{i}, a_{i+1}, \dots, a_{i+s})^T \in \mathbb{R}^{2s+1},
$$
that is the vector obtained in taking the neighborhood of $a_i$ with radius $s$ (with periodic boundary condition).

1. Write a function `array_to_patches_with_loop(a,s)` that constructs a matrix $M$ of size $2s+1\times d$ such that the $i$-th column of $M$ is the patch of $a$ at index $i$ using a for loop.

2. Write a function `array_to_patches_wo_loop(a,s)` that constructs the same matrix without any for loop.

3. Compare the time performance of the two functions as the size of $d$ grows using random signals. Report the result with a graph.

4. Create a signal with
```
n = 256
a = np.linspace(0,10,n) + np.random.randn(n)
```
Extract all the patches with half-size $s=7$ of $a$ and compute the mean of each patches to get a new signal $b\in\mathbb{R}^n$. Plot $a$ and $b$. Comment the result.
