<a href="https://colab.research.google.com/github/bgalerne/IoT_mathematics/blob/master/Lab2_linear_systems.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import time
import scipy.linalg

# Create some matrix $A$

In [18]:
n=5
M = np.random.rand(n,2*n)
print(M)
A = M.dot(M.T)
print(A)

[[0.33718307 0.63009354 0.4854541  0.09583345 0.51797124 0.7161584
  0.4468022  0.53344182 0.96494667 0.25220548]
 [0.95171826 0.2629077  0.6781226  0.95371519 0.4169272  0.00285753
  0.86112921 0.67733721 0.2597933  0.33855159]
 [0.01272154 0.14866683 0.45399696 0.42528438 0.34340806 0.09619981
  0.96209166 0.03314806 0.56637591 0.78017939]
 [0.15228491 0.58778139 0.25856138 0.6081899  0.19008433 0.49978307
  0.23252109 0.19750877 0.02103524 0.01483652]
 [0.73911768 0.11196978 0.07178123 0.66070592 0.87577513 0.29720724
  0.74030342 0.142055   0.97161736 0.88379503]]
[[3.01565914 2.20730335 1.79671975 1.29518193 2.65141158]
 [2.20730335 3.90058643 2.17031909 1.48001879 3.06300095]
 [1.79671975 2.17031909 2.39260791 0.83245879 2.62573273]
 [1.29518193 1.48001879 0.83245879 1.18508014 1.14751892]
 [2.65141158 3.06300095 2.62573273 1.14751892 4.149194  ]]


What are the properties of $A$?

Compute the $LU$ factorization using ```scipy.linalg.lu```.

The general code allows to change the order of the lines of $A$ in case the submatrix is not invertible at step $k$. 
In our case the permutation matrix will be identity (no line exchange).

Check that all the matrices have the expected form.

In [19]:
P, L, U = scipy.linalg.lu(A)
print(P)
print(L)
print(U)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[[ 1.          0.          0.          0.          0.        ]
 [ 0.73194723  1.          0.          0.          0.        ]
 [ 0.59579669  0.37428061  1.          0.          0.        ]
 [ 0.42948552  0.23283327 -0.13804752  1.          0.        ]
 [ 0.87921461  0.49117233  0.62469949 -0.34191611  1.        ]]
[[ 3.01565914  2.20730335  1.79671975  1.29518193  2.65141158]
 [ 0.          2.28495686  0.85521505  0.53201397  1.12230759]
 [ 0.          0.          1.00203781 -0.13832883  0.62597251]
 [ 0.          0.          0.          0.48585176 -0.16612054]
 [ 0.          0.          0.          0.          0.81894377]]


**Question:** What is done with the above line?

In [20]:
print(np.linalg.norm(L @ U-A, np.inf))

2.220446049250313e-16


# Solve a linear system with standard solver
The function ```np.linalg.solve``` solves a general linear system $Ax =b$.

In [21]:
b = np.random.rand(n)
xs = np.linalg.solve(A,b)
print(xs)


[-0.60279776 -0.0660419  -0.0765983   1.35896581  0.14515889]


**Exercise:**

Code a function ```solve_given_lu(b,L,U)``` that will solve $A x = b$ given the $LU$ factorization of $A$.
You should use the function ```scipy.linalg.solve_triangular``` for intermediary steps (read the doc).

In [22]:
def solve_given_lu(b,L,U):

  # TODO
  
  return(x)

print(solve_given_lu(b,L,U))

[-0.60279776 -0.0660419  -0.0765983   1.35896581  0.14515889]


# Performance for large size linear systems

In [16]:
n = 10 # up to 5*10**3
M = np.random.rand(n,2*n)
A = M.dot(M.T)
b = np.random.rand(n)

t = time.time()
P, L, U = scipy.linalg.lu(A)
print('Time for LU factorization:')
print(time.time()-t)

t = time.time()
xs = np.linalg.solve(A,b)
print('Time solving a system:')
print(time.time()-t)

t = time.time()
y = scipy.linalg.solve_triangular(L,b, lower=True)
x = scipy.linalg.solve_triangular(U,y)
print('Time solving with LU precomputed:')
print(time.time()-t)

print('Check error:')
print(np.linalg.norm(x-xs,np.inf))


Time for LU factorization:
0.026930809020996094
Time solving a system:
0.0005490779876708984
Time solving with LU precomputed:
0.0007128715515136719
Check error:
1.6653345369377348e-16


**Question:** For which size is it a efficient strategy to store the LU factorization if you have:
- 10 linear systems to solve with $A$?
- 2 linear systems to solve with $A$?

**Question:** Given the properties of $A$ what is a good alternative to $LU$ factorization? 

Do the same study with this alternative factorization.