<a href="https://colab.research.google.com/github/bgalerne/IoT_mathematics/blob/master/Lab2_linear_systems.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import time
import scipy.linalg

# Create some matrix $A$

In [2]:
n=5
M = np.random.rand(n,2*n)
print(M)
A = M.dot(M.T)
print(A)

[[0.90248683 0.76301785 0.62802274 0.42770629 0.88502724 0.06799525
  0.13009779 0.31650824 0.35161797 0.23361415]
 [0.78301785 0.55656948 0.47454412 0.66811003 0.50095522 0.89344761
  0.7354252  0.66032979 0.02287292 0.39396426]
 [0.87260417 0.99834433 0.36466263 0.20467584 0.4066677  0.35085654
  0.33478119 0.89735296 0.24736108 0.22946455]
 [0.76657442 0.77832598 0.38807316 0.36839892 0.60836787 0.88753907
  0.19817867 0.34378313 0.40747299 0.07424135]
 [0.06509969 0.05389877 0.48641584 0.60351689 0.52993751 0.29837845
  0.09890803 0.58748789 0.01619632 0.94640559]]
[[3.05723418 2.62397947 2.71775111 2.58096726 1.57838409]
 [2.62397947 3.7762711  3.00071546 2.97278187 2.0809702 ]
 [2.71775111 3.00071546 3.25264166 2.71434396 1.5131847 ]
 [2.58096726 2.97278187 2.71434396 2.96659091 1.38860583]
 [1.57838409 2.0809702  1.5131847  1.38860583 2.22871019]]


**Question:** What are the properties of $A$?

Compute the $LU$ factorization using ```scipy.linalg.lu```.

The general code allows to change the order of the lines of $A$ in case the submatrix is not invertible at step $k$. 
In our case the permutation matrix will be identity (no line exchange).

Check that all the matrices have the expected form.

In [4]:
P, L, U = scipy.linalg.lu(A)
print(P)
print(L)
print(U)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[[ 1.          0.          0.          0.          0.        ]
 [ 0.85828541  1.          0.          0.          0.        ]
 [ 0.88895745  0.43834945  1.          0.          0.        ]
 [ 0.84421641  0.49704847  0.1616207   1.          0.        ]
 [ 0.51627844  0.47650639 -0.38301892 -0.6832718   1.        ]]
[[ 3.05723418  2.62397947  2.71775111  2.58096726  1.57838409]
 [ 0.          1.52414781  0.66810935  0.75757534  0.72626617]
 [ 0.          0.          0.54381119  0.08789115 -0.20828998]
 [ 0.          0.          0.          0.39693931 -0.27121744]
 [ 0.          0.          0.          0.          0.80265981]]


**Question:** What is done with the above line?

In [5]:
print(np.linalg.norm(L @ U-A, np.inf))

4.440892098500626e-16


# Solve a linear system with standard solver
The function ```np.linalg.solve``` solves a general linear system $Ax =b$.

In [6]:
b = np.random.rand(n)
xs = np.linalg.solve(A,b)
print(xs)


[ 0.36219052  1.03055648  0.38896451 -1.35599856 -0.47075248]


**Exercise:**

Code a function ```solve_given_lu(b,L,U)``` that will solve $A x = b$ given the $LU$ factorization of $A$.
You should use the function ```scipy.linalg.solve_triangular``` for intermediary steps (read the doc).

In [ ]:
def solve_given_lu(b,L,U):

  # TODO
  
  return(x)

print(solve_given_lu(b,L,U))

# Performance for large size linear systems

In [ ]:
n = 10 # up to 5*10**3
M = np.random.rand(n,2*n)
A = M.dot(M.T)
b = np.random.rand(n)

t = time.time()
P, L, U = scipy.linalg.lu(A)
print('Time for LU factorization:')
print(time.time()-t)

t = time.time()
xs = np.linalg.solve(A,b)
print('Time solving a system:')
print(time.time()-t)

t = time.time()
y = scipy.linalg.solve_triangular(L,b, lower=True)
x = scipy.linalg.solve_triangular(U,y)
print('Time solving with LU precomputed:')
print(time.time()-t)

print('Check error:')
print(np.linalg.norm(x-xs,np.inf))


**Question:** For which size is it an efficient strategy to store the LU factorization if you have:
- 10 linear systems to solve with $A$?
- 2 linear systems to solve with $A$?

**Question:** Given the properties of $A$ what is a good alternative to $LU$ factorization? 

Do the same study with this alternative factorization.